const languages = [
  {
    no: "1",
    name: "English",
    native: "English",
    code: "en",
    audioDetection: true,
  },
  {
    no: "2",
    name: "Chinese",
    native: "中文简体",
    code: "zh",
  },
  {
    no: "3",
    name: "Dutch",
    native: "Nederlands",
    code: "nl",
    audioDetection: true,
  },
  {
    no: "4",
    name: "Finnish",
    native: "Suomi",
    code: "fi",
  },
  {
    no: "5",
    name: "French",
    native: "Français",
    code: "fr",
    audioDetection: true,
  },
  {
    no: "6",
    name: "German",
    native: "Deutsch",
    code: "de",
    audioDetection: true,
  },
  {
    no: "7",
    name: "Hindi",
    native: "हिन्दी",
    code: "hi",
  },
  {
    no: "8",
    name: "Italian",
    native: "Italiano",
    code: "it",
    audioDetection: true,
  },
  {
    no: "9",
    name: "Japanese",
    native: "日本語",
    code: "ja",
  },
  {
    no: "10",
    name: "Korean",
    native: "한국어",
    code: "ko",
  },
  {
    no: "11",
    name: "Polish",
    native: "Polski",
    code: "pl",
  },
  {
    no: "12",
    name: "Portuguese",
    native: "Português",
    code: "pt",
    audioDetection: true,
  },
  {
    no: "13",
    name: "Russian",
    native: "Русский",
    code: "ru",
  },
  {
    no: "14",
    name: "Spanish",
    native: "Español",
    code: "es",
    audioDetection: true,
  },
  {
    no: "15",
    name: "Turkish",
    native: "Türkçe",
    code: "tr",
  },
  {
    no: "16",
    name: "Ukrainian",
    native: "Українська",
    code: "uk",
  },
  {
    no: "17",
    name: "Vietnamese",
    native: "Tiếng Việt",
    code: "vi",
  },
];

export default languages;
